#!/usr/bin/env python

# SPDX-FileCopyrightText: 2020 Pier Luigi Fiorini <pierluigi.fiorini@liri.io>
#
# SPDX-License-Identifier: MIT

import os
import json

def main():
    github_workspace = os.environ['GITHUB_WORKSPACE']
    sources_path = os.environ.get('INPUT_SOURCES_PATH') or os.path.join(github_workspace, '.tx', 'sources.json')

    with open(sources_path, 'r') as f:
        sources = json.load(f)
        for entry in sources:
            args = ['lupdate', entry['directory'], '-ts', '-no-obsolete', entry['output_path']]
            os.system(' '.join(args))

if __name__ == '__main__':
    main()
